name = "libsql"
version = "0.0.1"
target = "javascript"
description = "An unofficial Gleam port of turso's libSQL library"
licenses = ["MIT"]
version = "0.0.1"
repository = { type = "github", user = "brunoti", repo = "libsql" }
links = [
  { title = "About the creator", href = "https://bop.systems" },
]
internal_modules = [
]

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_javascript = "~> 0.8"

[dev-dependencies]
gleeunit = "~> 1.0"
